---

- name: copy jdk-8u152 package to server
  copy: src=../file/jdk-8u152-linux-x64.rpm dest=/tmp/jdk-8u152-linux-x64.rpm

- name: install jdk-8u152
  yum:  name=/tmp/jdk-8u152-linux-x64.rpm state=present
