---

- hosts: init
  vars:
    disk: /dev/xvdb
    partition: /dev/xvdb1
    mountDir: /data
  remote_user: root
#  gather_facts: False
#  sudo: yes
  roles:
  - { role: common, tags: [ "common" ] }

- hosts: zabbix
  remote_user: root
  roles:
  - { role: zabbix, tags: [ "zabbix" ] }

- hosts: mysql
  remote_user: root
  roles:
  - { role: mysql, tags: [ "mysql" ] }

- hosts: mongo
  remote_user: root
  roles:
  - { role: mongo, tags: [ "mongo" ] }

- hosts: redis
  remote_user: root
  roles:
  - { role: redis, tags: [ "redis" ] }
